<?php

namespace App\Models\InternationalFlight;

use Illuminate\Database\Eloquent\Model;

class FlightBooking extends Model
{
    protected $fillable = [
        'search_flight_id',
        'pnr_id',
        'ticket_status',
        'contact_details',
        'air_price',
        'booking_code',
        'flights',
        'org_pricing',
        'ticket_details',
        'payment_status',
        'pnr_void',
        'ticket_cancel',
        'ticket_void_count',
        'agent_markup',
        'airline',
        'currency',
        'trip_type',
        'bsp_fare',
        'final_fare',
        'flight_date',
        'ticket_itineraries',
        'is_office_staff',
        'for_payment',
        'api_provider',
        'airiq_booking_details',
        'airiq_pricing_details',
        'airiq_flights_details',
        'airiq_ticket_details',
        'airiq_flight_type',
    ];
    protected $appends = [
        'adults',
        'childs',
        'infants',
        'paid_amount'
    ];

    public function getAdultsAttribute()
    {
        return $this->bookingDetails()->where('pax_type', 'ADT')->count();
    }

    public function bookingDetails()
    {
        return $this->hasMany('App\Models\InternationalFlight\FlightBookingDetail', 'flight_booking_id');
    }

    public function getChildsAttribute()
    {
        return $this->bookingDetails()->where('pax_type', 'CHLD')->count();
    }

    public function getInfantsAttribute()
    {
        return $this->bookingDetails()->where('pax_type', 'INFT')->count();
    }

    public function ofSearch()
    {
        return $this->belongsTo('App\Models\InternationalFlight\SearchFlight', 'search_flight_id');
    }

    public function bookedBy()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }

    public function getTickets()
    {
        return $this->hasMany('App\Models\InternationalFlight\FlightTicket', 'flight_booking_id');
    }

    public function getPaidAmountAttribute()
    {
        if ($this->payments()->get()->count() > 0) {
            $totalAmount = 0;
            foreach ($this->payments()->get() as $payment) {
                $totalAmount += $payment->amount;
            }
            return $totalAmount;
        } else {
            return 0;
        }
    }

    public function payments()
    {
        return $this->morphMany('App\Models\Finance\Payment', 'booking');
    }

    public function getPaxDetail($booking_id, $f_name, $l_name)
    {
        return FlightBookingDetail::where(['flight_booking_id' => $booking_id, 'pax_first_name' => $f_name, 'pax_last_name' => $l_name])->first(); // TODO: Change the autogenerated stub
    }

    const phone_code = [
        "Nepal" => "977",
        "India" => "91",
        "Afghanistan" => "93",
        "Albania" => "355",
        "Algeria" => "213",
        "American Samoa" => "1-684",
        "Andorra" => "376",
        "Angola" => "244",
        "Anguilla" => "1-264",
        "Antigua and Barbuda" => "1-268",
        "Argentina" => "54",
        "Armenia" => "374",
        "Aruba" => "297",
        "Ascension" => "247",
        "Australia" => "61",
        "Austria" => "43",
        "Azerbaijan" => "994",
        "Bahamas" => "1-242",
        "Bahrain" => "973",
        "Bangladesh" => "880",
        "Barbados" => "1-246",
        "Belarus" => "375",
        "Belgium" => "32",
        "Belize" => "501",
        "Benin" => "229",
        "Bermuda" => "1-441",
        "Bhutan" => "975",
        "Bolivia" => "591",
        "Bosnia and Herzegovina" => "387",
        "Botswana" => "267",
        "Brazil" => "55",
        "British Virgin Islands" => "1-284",
        "Brunei" => "673",
        "Bulgaria" => "359",
        "Burkina Faso" => "226",
        "Burundi" => "257",
        "Cambodia" => "855",
        "Cameroon" => "237",
        "Canada" => "1",
        "Cape Verde" => "238",
        "Cayman Islands" => "1-345",
        "Central African Republic" => "236",
        "Chad" => "235",
        "Chile" => "56",
        "China" => "86",
        "Colombia" => "57",
        "Comoros" => "269",
        "Cook Islands" => "682",
        "Costa Rica" => "506",
        "Côte d'Ivoire" => "225",
        "Croatia" => "385",
        "Cuba" => "53",
        "Cyprus" => "357",
        "Czech Republic" => "420",
        "Democratic Republic of the Congo" => "243",
        "Denmark" => "45",
        "Djibouti" => "253",
        "Dominica" => "1-767",
        "Dominican Republic" => "1-809",
        "Ecuador" => "593",
        "Egypt" => "20",
        "El Salvador" => "503",
        "Equatorial Guinea" => "240",
        "Eritrea" => "291",
        "Estonia" => "372",
        "Ethiopia" => "251",
        "Falkland Islands" => "500",
        "Faroe Islands" => "298",
        "Fiji" => "679",
        "Finland" => "358",
        "France" => "33",
        "French Guiana" => "594",
        "French Polynesia" => "689",
        "Gabon" => "241",
        "Gambia" => "220",
        "Georgia" => "995",
        "Germany" => "49",
        "Ghana" => "233",
        "Gibraltar" => "350",
        "Greece" => "30",
        "Greenland" => "299",
        "Guadeloupe" => "590",
        "Guam" => "1-671",
        "Guatemala" => "502",
        "Guinea" => "224",
        "Guinea-Bissau" => "245",
        "Guyana" => "592",
        "Haiti" => "509",
        "Honduras" => "504",
        "Hong Kong" => "852",
        "Hungary" => "36",
        "Iceland" => "354",
        "Indonesia" => "62",
        "Iran" => "98",
        "Iraq" => "964",
        "Ireland" => "353",
        "Israel" => "972",
        "Italy" => "39",
        "Jamaica" => "1-876",
        "Japan" => "81",
        "Jordan" => "962",
        "Kazakhstan" => "7",
        "Kenya" => "254",
        "Kiribati" => "686",
        "Korea, South" => "82",
        "Kuwait" => "965",
        "Kyrgyzstan" => "996",
        "Laos" => "856",
        "Latvia" => "371",
        "Lebanon" => "961",
        "Lesotho" => "266",
        "Liberia" => "231",
        "Libya" => "218",
        "Liechtenstein" => "423",
        "Lithuania" => "370",
        "Luxembourg" => "352",
        "Macao" => "853",
        "Madagascar" => "261",
        "Malawi" => "265",
        "Malaysia" => "60",
        "Maldives" => "960",
        "Mali" => "223",
        "Malta" => "356",
        "Marshall Islands" => "692",
        "Martinique" => "596",
        "Mauritania" => "222",
        "Mauritius" => "230",
        "Mayotte" => "269",
        "Mexico" => "52",
        "Micronesia" => "691",
        "Moldova" => "373",
        "Monaco" => "377",
        "Mongolia" => "976",
        "Montenegro" => "382",
        "Morocco" => "212",
        "Mozambique" => "258",
        "Myanmar" => "95",
        "Namibia" => "264",
        "Nauru" => "674",
        "Netherlands" => "31",
        "New Caledonia" => "687",
        "New Zealand" => "64",
        "Nicaragua" => "505",
        "Niger" => "227",
        "Nigeria" => "234",
        "North Korea" => "850",
        "North Macedonia" => "389",
        "Norway" => "47",
        "Oman" => "968",
        "Pakistan" => "92",
        "Palau" => "680",
        "Panama" => "507",
        "Papua New Guinea" => "675",
        "Paraguay" => "595",
        "Peru" => "51",
        "Philippines" => "63",
        "Poland" => "48",
        "Portugal" => "351",
        "Puerto Rico" => "1-787",
        "Qatar" => "974",
        "Réunion" => "262",
        "Romania" => "40",
        "Russia" => "7",
        "Rwanda" => "250",
        "Saint Helena" => "290",
        "Saint Kitts and Nevis" => "1-869",
        "Saint Lucia" => "1-758",
        "Saint Vincent and the Grenadines" => "1-784",
        "Samoa" => "685",
        "San Marino" => "378",
        "Sao Tome and Principe" => "239",
        "Saudi Arabia" => "966",
        "Senegal" => "221",
        "Serbia" => "381",
        "Seychelles" => "248",
        "Sierra Leone" => "232",
        "Singapore" => "65",
        "Slovakia" => "421",
        "Slovenia" => "386",
        "Solomon Islands" => "677",
        "Somalia" => "252",
        "South Africa" => "27",
        "Spain" => "34",
        "Sri Lanka" => "94",
        "Sudan" => "249",
        "Suriname" => "597",
        "Swaziland" => "268",
        "Sweden" => "46",
        "Switzerland" => "41",
        "Syria" => "963",
        "Taiwan" => "886",
        "Tajikistan" => "992",
        "Tanzania" => "255",
        "Thailand" => "66",
        "Timor-Leste" => "670",
        "Togo" => "228",
        "Tonga" => "676",
        "Trinidad and Tobago" => "1-868",
        "Tunisia" => "216",
        "Turkey" => "90",
        "Turkmenistan" => "993",
        "Tuvalu" => "688",
        "Uganda" => "256",
        "Ukraine" => "380",
        "United Arab Emirates" => "971",
        "United Kingdom" => "44",
        "United States" => "1",
        "Uruguay" => "598",
        "Uzbekistan" => "998",
        "Vanuatu" => "678",
        "Vatican City" => "379",
        "Venezuela" => "58",
        "Vietnam" => "84",
        "Wallis and Futuna" => "681",
        "Yemen" => "967",
        "Zambia" => "260",
        "Zimbabwe" => "263",
    ];
}
