<?php

namespace App\Models\InternationalFlight;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;

class FlightTicket extends Model
{
    protected $fillable = [
        'flight_booking_id',
        'pax_type',
        'first_name',
        'last_name',
        'ticket_number',
        'ticket_reference',
        'rph',
        'status',
        'void_date',
        'voided_by'
    ];

    protected $appends = ['full_name'];

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function ofBooking()
    {
        return $this->belongsTo(FlightBooking::class, 'flight_booking_id');
    }

    public function voidedBy()
    {
        return $this->belongsTo(User::class, 'voided_by')->withTrashed();
    }
    public function getPaxDetail($booking_id, $f_name,$l_name)
    {
        return FlightBookingDetail::where(['flight_booking_id'=>$booking_id,'pax_first_name'=>$f_name,'pax_last_name'=>$l_name])->first(); // TODO: Change the autogenerated stub
    }
}
